# Feature: poseidon-smart-water-hub, Property 6: Alert payload structural completeness
# Validates: Requirements 3.2

# Feature: poseidon-smart-water-hub, Property 7: Alert type validity
# Validates: Requirements 3.3

from hypothesis import given, settings
from hypothesis import strategies as st

from optical_sentry import build_alert_payload

VALID_ALERT_TYPES = [
    "Contaminant Detected",
    "Pipe Blockage",
    "Severe Discoloration",
    "Foreign Object",
]


# Property 6: Alert payload structural completeness
@settings(max_examples=100)
@given(st.integers())
def test_alert_payload_structural_completeness(seed):
    """
    For any Alert_Payload generated by the Edge Node, the payload SHALL
    contain all required fields with the correct types and value ranges.
    Validates: Requirements 3.2
    """
    payload = build_alert_payload("test-node", seed=seed)

    # All required fields must be present
    assert "node_id" in payload
    assert "timestamp" in payload
    assert "alert_type" in payload
    assert "confidence_score" in payload
    assert "raw_detection_json" in payload

    # Type assertions
    assert isinstance(payload["node_id"], str)
    assert isinstance(payload["timestamp"], str)
    assert isinstance(payload["alert_type"], str)
    assert isinstance(payload["confidence_score"], float)
    assert isinstance(payload["raw_detection_json"], dict)

    # confidence_score must be in [0.0, 1.0]
    assert 0.0 <= payload["confidence_score"] <= 1.0


# Property 7: Alert type validity
@settings(max_examples=100)
@given(st.integers())
def test_alert_type_validity(seed):
    """
    For any Alert_Payload generated by the Edge Node, the alert_type field
    SHALL be one of the four valid alert type values.
    Validates: Requirements 3.3
    """
    payload = build_alert_payload("test-node", seed=seed)

    assert payload["alert_type"] in VALID_ALERT_TYPES
