ALTER TABLE IF EXISTS "Rainfall_Log"
  ADD COLUMN IF NOT EXISTS sensor_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS message_id TEXT;

ALTER TABLE IF EXISTS "Storage_Tanks"
  ADD COLUMN IF NOT EXISTS fill_percent NUMERIC(6,2),
  ADD COLUMN IF NOT EXISTS sensor_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS message_id TEXT;

ALTER TABLE IF EXISTS "Quality_Sensors"
  ADD COLUMN IF NOT EXISTS alert_level VARCHAR(16) NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS message_id TEXT;

ALTER TABLE IF EXISTS "Irrigation_Zones"
  ADD COLUMN IF NOT EXISTS sensor_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS message_id TEXT;

ALTER TABLE IF EXISTS "Overall_Usage"
  ADD COLUMN IF NOT EXISTS sensor_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS message_id TEXT;

ALTER TABLE IF EXISTS "Anomaly_Alerts"
  ADD COLUMN IF NOT EXISTS sensor_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS message_id TEXT,
  ADD COLUMN IF NOT EXISTS payload_json JSONB NOT NULL DEFAULT '{}'::jsonb;
